/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabodega;

/**
 *
 * @author Javier
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsalir = new javax.swing.JButton();
        btninrgesar = new javax.swing.JButton();
        btn_venta = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        fondopantalla = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jopciones = new javax.swing.JMenu();
        jmenu = new javax.swing.JMenuItem();
        jayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsalir.setText("SALIR");
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        btninrgesar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btninrgesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new_file.png"))); // NOI18N
        btninrgesar.setText("INGRESAR");
        btninrgesar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninrgesar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btninrgesar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btninrgesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninrgesarActionPerformed(evt);
            }
        });
        getContentPane().add(btninrgesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 200, 200));

        btn_venta.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btn_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Line_ui_icons_Svg-10_icon-icons.com_72171 (1).png"))); // NOI18N
        btn_venta.setText("VENTA");
        btn_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_venta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_venta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 200, 200));

        btnmodificar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/writing_file.png"))); // NOI18N
        btnmodificar.setText("MODIFICAR");
        btnmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 200, 200));

        btnbuscar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/my_documents.png"))); // NOI18N
        btnbuscar.setText("BUSCAR");
        btnbuscar.setBorder(null);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 200, 200));

        fondopantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Abstract-Minimalist-Shapes-4k.jpg"))); // NOI18N
        getContentPane().add(fondopantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 540));

        jopciones.setText("Opciones");
        jopciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        jmenu.setText("Menu");
        jmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });
        jopciones.add(jmenu);

        jMenuBar1.add(jopciones);

        jayuda.setText("Ayuda");
        jayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(jayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        Login l=new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btninrgesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninrgesarActionPerformed
        // TODO add your handling code here:
        V_INGRESAR i=new V_INGRESAR();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btninrgesarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        Buscar b=new Buscar();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btn_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ventaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_venta;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btninrgesar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel fondopantalla;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jayuda;
    private javax.swing.JMenuItem jmenu;
    private javax.swing.JMenu jopciones;
    // End of variables declaration//GEN-END:variables
}
