/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabodega;
import Objetos.objeto;
import Registros.RegistroVenta;
import Conexion.conexion;

/**
 *
 * @author Javier
 */
public class V_INGRESAR extends javax.swing.JFrame {

    /**
     * Creates new form V_INGRESAR
     */
    public V_INGRESAR() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        na1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        nombre1 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        nombre2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        nombre3 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        nombre4 = new javax.swing.JLabel();
        cboxtipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fondopantalla1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jopciones = new javax.swing.JMenu();
        jmenu = new javax.swing.JMenuItem();
        jayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        na1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        na1.setForeground(new java.awt.Color(255, 255, 255));
        na1.setText("INGRESO INVENTARIO");
        getContentPane().add(na1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("NOMBRE :");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 290, -1));

        nombre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre1.setForeground(new java.awt.Color(255, 255, 255));
        nombre1.setText("VALOR :");
        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 80, -1));

        nombre2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre2.setForeground(new java.awt.Color(255, 255, 255));
        nombre2.setText("SERIAL :");
        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 120, -1));

        nombre3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre3.setForeground(new java.awt.Color(255, 255, 255));
        nombre3.setText("RESTRICCION :");
        getContentPane().add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));
        getContentPane().add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 290, -1));

        nombre4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre4.setForeground(new java.awt.Color(255, 255, 255));
        nombre4.setText("DESCRIPCION :");
        getContentPane().add(nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        cboxtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "E", "E10+", "T", "M", "AO", "RP" }));
        cboxtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxtipoActionPerformed(evt);
            }
        });
        getContentPane().add(cboxtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 170, -1));

        jButton1.setText("INRGESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 170, 50));

        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FriendBot.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        fondopantalla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Abstract-Minimalist-Shapes-4k.jpg"))); // NOI18N
        getContentPane().add(fondopantalla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jopciones.setText("Opciones");

        jmenu.setText("Menu");
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });
        jopciones.add(jmenu);

        jMenuBar1.add(jopciones);

        jayuda.setText("Ayuda");
        jMenuBar1.add(jayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtnombre.setText(null);
        txtmarca.setText(null);
        txtcantidad.setText(null);
        txtcodigo.setText(null);
        cboxtipo.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tipo = "";
        objeto o = new objeto();
        int ser = Integer.parseInt(txtcodigo.getText());
        o.setSerial(ser);
        o.setNombre(this.txtnombre.getText().trim());
        o.setDescripcion(this.txtmarca.getText().trim());
        tipo = cboxtipo.getSelectedItem().toString();
        o.setRestriccion(tipo.trim());
        o.setValor(Integer.parseInt(this.txtcantidad.getText().trim()));
        if(RegistroVenta.agregarVenta(o))
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Objeto Ingresado al Inventario  :)");
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "[ERROR] No pudo ser Guardado  :( ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboxtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxtipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_INGRESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_INGRESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_INGRESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_INGRESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_INGRESAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxtipo;
    private javax.swing.JLabel fondopantalla1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jayuda;
    private javax.swing.JMenuItem jmenu;
    private javax.swing.JMenu jopciones;
    private javax.swing.JLabel na1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JLabel nombre4;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
