/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabodega;
import Objetos.objeto;
import Registros.RegistroVenta;
import Conexion.conexion;
import Controlador.Controlador;
import Controlador.Correo;
import Objetos.venta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javier
 */
public class V_VENTA extends javax.swing.JFrame {

    /**
     * Creates new form V_INGRESAR
     */
    public V_VENTA() {
        initComponents();
        this.setLocationRelativeTo(null);
        ArrayList<objeto> listainventario = RegistroVenta.mostrarVentas();
        for (int i = 0; i < listainventario.size(); i++) {
            cbox_juego.addItem(listainventario.get(i).getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        na1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        txt_cant = new javax.swing.JTextField();
        nombre2 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        cbox_juego = new javax.swing.JComboBox<>();
        btn_asept = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        na2 = new javax.swing.JLabel();
        btn_confirm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondopantalla1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jopciones = new javax.swing.JMenu();
        jmenu = new javax.swing.JMenuItem();
        jayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        na1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        na1.setForeground(new java.awt.Color(255, 255, 255));
        na1.setText("DondePanxitoGames");
        getContentPane().add(na1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("JUEGO:");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        nombre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre1.setForeground(new java.awt.Color(255, 255, 255));
        nombre1.setText("CANTIDAD:");
        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));
        getContentPane().add(txt_cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 140, -1));

        nombre2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre2.setForeground(new java.awt.Color(255, 255, 255));
        nombre2.setText("CORREO:");
        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 130, -1));

        cbox_juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_juegoActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 170, -1));

        btn_asept.setText("CONFIRMAR");
        btn_asept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_asept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aseptActionPerformed(evt);
            }
        });
        getContentPane().add(btn_asept, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 140, 30));

        btn_clear.setText("LIMPIAR");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 100, 40));

        na2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        na2.setForeground(new java.awt.Color(255, 255, 255));
        na2.setText("VENTA");
        getContentPane().add(na2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, -1));

        btn_confirm.setText("PAGAR");
        btn_confirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 100, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Boleta N°", "Correo", "Juego", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FriendBot.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Juego a Comprar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, -1, -1));

        fondopantalla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Abstract-Minimalist-Shapes-4k.jpg"))); // NOI18N
        getContentPane().add(fondopantalla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jopciones.setText("Opciones");
        jopciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        jmenu.setText("Menu");
        jmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });
        jopciones.add(jmenu);

        jMenuBar1.add(jopciones);

        jayuda.setText("Ayuda");
        jayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(jayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_cant.setText("");
        txt_correo.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_aseptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aseptActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        String correo=txt_correo.getText();
        String juego = cbox_juego.getSelectedItem().toString();
        int cant = Integer.parseInt(txt_cant.getText());
        String qry = "SELECT * FROM game WHERE nombre = "+"'"+juego+"'";
        System.out.println("SELECT valor FROM game WHERE nombre = "+"'"+juego+"'");
        ArrayList<objeto> listainventario = RegistroVenta.mostrarValor(qry);
        String resultado = "";
        int total_aux=0;
        int total;
        int boleta=0;
        for(int i = 0; i < listainventario.size(); i++) {
            total_aux = listainventario.get(i).getValor();
            boleta = listainventario.get(i).getSerial();
            System.out.println(total_aux +" / "+ boleta);
            if (cant != 1) {
                total = cant * total_aux;
            }else{
                total = total_aux;
            }
            modelo.addRow(new Object[]{boleta,correo,juego,cant,total});
        }
    }//GEN-LAST:event_btn_aseptActionPerformed

    private void cbox_juegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_juegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_juegoActionPerformed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        String correo=txt_correo.getText();
        String juego = cbox_juego.getSelectedItem().toString();
        int cant = Integer.parseInt(txt_cant.getText());
        String qry = "SELECT * FROM game WHERE nombre = "+"'"+juego+"'";
        System.out.println("SELECT valor FROM game WHERE nombre = "+"'"+juego+"'");
        ArrayList<objeto> listainventario = RegistroVenta.mostrarValor(qry);
        String resultado = "";
        int total_aux=0;
        int total;
        int boleta=0;
        
        String send_correo,send_juego;
        int send_id,send_cantidad,send_total;
        
        for(int i = 0; i < listainventario.size(); i++) {
            total_aux = listainventario.get(i).getValor();
            boleta = listainventario.get(i).getSerial();
            System.out.println(total_aux +" / "+ boleta);
            if (cant != 1) {
                total = cant * total_aux;
            }else{
                total = total_aux;
            }
        venta v = new venta();
        v.setCorreo(correo);
        v.setJuego(juego);
        v.setCantidad(cant);
        v.setTotal(total);
        
            if(RegistroVenta.agregarCompraVenta(v))
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Venta Ingresada al Inventario  :)");
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(this, "[ERROR] No pudo ser Guardado  :( ");
            }
            
            String qrysend = "SELECT * FROM venta WHERE correo = "+"'"+correo+"'";
            ArrayList<venta> listaventa = RegistroVenta.EnviarDatos(qrysend);
            
            for(int x = 0; i < listaventa.size(); i++) {
                send_id = listaventa.get(x).getId();
                send_correo = listaventa.get(x).getCorreo();
                send_juego = listaventa.get(x).getJuego();
                send_cantidad = listaventa.get(x).getCantidad();
                send_total = listaventa.get(x).getTotal();
                
                Correo c=new Correo();
                
                c.setContraseña("ymzzmvzgxqymatrb");
                c.setUsuariocorreo("bodegatemporalcuadroverde@gmail.com");
                c.setAsunto("Compra Finalizada #"+send_id);
                c.setMensaje("Gracias. Aquí está su recibo del pago realizado con respecto al pedido en DondePanxitoGames. \n"+
                            "Hola,"+send_correo+" \n"+
                            "Su compra ha sido procesada con éxito."+"\n"+
                            "\n"+
                            "Resumen de Compra"+"\n"+
                            "Numero de la Compra: "+send_id+"\n"+
                            "Juego: "+send_juego+"\n"+
                            "Total: $"+send_total);
                c.setDestino(send_correo);
                c.setNombreArchivo("FriendBot.png");
                c.setRutaArchivo("FriendBot.png");
                Controlador co=new Controlador();
                co.enviarCorreo(c);
                if(co.enviarCorreo(c)){
                    JOptionPane.showMessageDialog(null, "Envio Correo");
                }else{
                   JOptionPane.showMessageDialog(null, "Error"); 
                }
            }
        }
    }//GEN-LAST:event_btn_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_VENTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_asept;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JComboBox<String> cbox_juego;
    private javax.swing.JLabel fondopantalla1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu jayuda;
    private javax.swing.JMenuItem jmenu;
    private javax.swing.JMenu jopciones;
    private javax.swing.JLabel na1;
    private javax.swing.JLabel na2;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JTextField txt_cant;
    private javax.swing.JTextField txt_correo;
    // End of variables declaration//GEN-END:variables
}
